### ISSUE TITLE
Problem with Int::ModInv function

### ISSUE THREAD

**Issue by bojlahg** [JeanLucPons/VanitySearch#113]
If rewrite this function as Int::ModInvK1order() to use _O instead of _P.
It works correct mod inv for 2:
7FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF5D576E7357A4501DDFE92F46681B20A1
But it produces wrong result for 3:
82BF7F39A4D8106748D1A88032817BE8BD439FCAF491B982B7AC082B9D33ABF6
Correct result:
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9D1C9E899CA306AD27FE1945DE0242B81

In case of switch to XCD instead of DSR62 it works fine.

**Comment by bojlahg** [comment]
ok found: MM32 & MM64 constants should be initialized accordingly...
DSR62 works fine.

**Comment by JeanLucPons** [comment]
Cool.
You have in Int::Check() the test with prime=curve order (you have to comment in/out) the follwinfglines.
https://github.com/JeanLucPons/VanitySearch/blob/1bc508a19e2066777f3fb1a020f68f8705daf0f4/Int.cpp#L1550
