### ISSUE TITLE
What is the SSE is for?

### ISSUE THREAD

**Issue by greg2paris** [JeanLucPons/VanitySearch#117]
Hello, I tried the code with and without the sse but I canot see the difference.
What is the advantage of using SSE?
Is it faster or slower?

**Comment by phrutis** [comment]
the parameter for the cpu which gives an error in the program.

**Comment by greg2paris** [comment]
But do you know what is the use of it ?
I looked at the code it seems to calculate 4 keys at the same time but it doesnt affect the speed when I am using gpu.

**Comment by marssystems** [comment]
SSE is a processor technology that enables single instruction multiple data. Older processors only process a single data element per instruction. SSE enables the instruction to handle multiple data elements. It's used in intensive applications, such as 3D graphics, for faster processing.

SSE is designed to replace MMX™ Technology. It expanded over the generations of Intel® Processors to include SSE2, SSE3/SSE3S, and SSE4. Each iteration has brought new instructions and increased performance.

Not used by the GPU.

**Comment by greg2paris** [comment]
Ok, I see, thank you for the answer.
