### ISSUE TITLE
Limiting stack size

### ISSUE THREAD

**Issue by aaelick** [JeanLucPons/VanitySearch#141]
size_t stackSize = 49152;
err = cudaDeviceSetLimit(cudaLimitStackSize, stackSize);
if (err != cudaSuccess) {
  printf("GPUEngine: %s\n", cudaGetErrorString(err));
  return;
}

Can this be removed? Why limiting stack size needed? 
By removing these lines on moderm hardware gpu memory allocation a lot smaller.

**Comment by Kempeter** [comment]
If you delete these lines, you have to do some tests, because it risks runtime failures if your kernels need more stack space than the default. => removing these lines might lead to failures

**Comment by aaelick** [comment]
Already work ok without this lines for over 2 month.
