### ISSUE TITLE
 Pollard  Rho

### ISSUE THREAD

**Issue by dem10** [JeanLucPons/VanitySearch#19]
Dear Jean-Luc, Is it possible to make Pollard Rho in language OpenQASM?
https://developer.ibm.com/code/2017/05/17/developers-guide-to-quantum-qiskit-sdk/

**Comment by broka77** [comment]
any news? The author has disappeared somewhere)

**Comment by dem10** [comment]
The author deals with Pollard Rho for a home computer.

**Comment by neutron220** [comment]
> any news? The author has disappeared somewhere)

![image](https://user-images.githubusercontent.com/50183263/57569766-887a8c00-7402-11e9-8c07-a5ecf36bdd9e.png)
