### ISSUE TITLE
How to specify multiple gpuId?

### ISSUE THREAD

**Issue by jRazer** [JeanLucPons/VanitySearch#2]
It is possible to use several gpu to search at all in one process

**Comment by JeanLucPons** [comment]
Hello,
Not yet, I will try to add this.
I let you informed

**Comment by successhalf** [comment]
Your great idea
I think it needs some extra functionality
-i input.txt    1Test
-o output.txt  1Testa3r7d1FF4o5pbWYiUSqBdMWMq9MY |  5HqwuFbQLsuthXpTTTqwYQuM5vVL7jb1DXqAMNGwoa1DAicdokn
-D 0:0  0:1 0:2     GPU

**Comment by JeanLucPons** [comment]
Ok
For multiple GPU, I think to allow a list of Id with the -gpuId option. (i.e. -gpuId 0,2,3,4)
I will definitely add ouput file for generated keys.
For the input file, I will see, there's no plan yet to implement multiple prefix search, but I will see.

**Comment by successhalf** [comment]
> Ok
> For multiple GPU, I think to allow a list of Id with the -gpuId option. (i.e. -gpuId 0,2,3,4)
> I will definitely add ouput file for generated keys.
> For the input file, I will see, there's no plan yet to implement multiple prefix search, but I will see.

yeah
Could be perfect

**Comment by Simkas45** [comment]
Please release -i input.txt 1Test

**Comment by JeanLucPons** [comment]
> 
> 
> Please release -i input.txt 1Test

What do you expect exactly ?
You want an input file containing a list of prefix to search ?
If yes, I have to restructure a lot the architecture of the code to support multi-prefix. This is not obvious but I will see if I can do something.

**Comment by JeanLucPons** [comment]
> 
> 
> > Ok
> > For multiple GPU, I think to allow a list of Id with the -gpuId option. (i.e. -gpuId 0,2,3,4)
> > I will definitely add ouput file for generated keys.
> > For the input file, I will see, there's no plan yet to implement multiple prefix search, but I will see.
> 
> yeah
> Could be perfect

Done
I will restructure the code in order to optimize memory transfer between GPU and CPU, that should also ease the management of multiple prefix search. 
I close the issue
