### ISSUE TITLE
Specify keyspace

### ISSUE THREAD

**Issue by ZielarSRC** [JeanLucPons/VanitySearch#23]
Hello. Can i specify in command line keyspace when i would like to scan for find key to selected prefix?

**Comment by JeanLucPons** [comment]
Not yet

**Comment by poseidondev** [comment]
Hey if you added this feature, this software would be awesome for the bitcoin puzzle transaction :) Here is the code that adds the keyspace feature in bitcrack: https://github.com/brichard19/BitCrack/tree/master/KeyFinder
