### ISSUE TITLE
Setting up your own seed does not work.

### ISSUE THREAD

**Issue by ZielarSRC** [JeanLucPons/VanitySearch#32]
I do not know how the use of non-random Basekey works. I set up, let's assume 999999999999999, and he's still taking BASEKEY CEC35CA3247CEC35CA3247CEC35CA3247CEC35CA3247CEC35CA3247. How do I actually set the Basekey to the one I want to set myself?

**Comment by JeanLucPons** [comment]
Hello,
In the present release, no way to set up a base key by hand.

**Comment by 1000Bursh** [comment]
Pollard_s kangaroo-Windows 10 -Ubuntu 18.04 LTS
https://github.com/pikachunakopika/Pollard_s-kangaroo

> Hello,

Pollard_s kangaroo-Windows 10 -Ubuntu 18.04 LTS
https://github.com/pikachunakopika/Pollard_s-kangaroo

**Comment by 1000Bursh** [comment]
Hi.
Pollard_s kangaroo-Windows 10 -Ubuntu 18.04 LTS
https://github.com/pikachunakopika/Pollard_s-kangaroo

**Comment by dem10** [comment]
> Hi.
> Pollard_s kangaroo-Windows 10 -Ubuntu 18.04 LTS
> https://github.com/pikachunakopika/Pollard_s-kangaroo

scam

**Comment by Jessie-1** [comment]
@JeanLucPons please enable the option. Its possible to solve #64 of the puzzel
