### ISSUE TITLE
error when compiling

### ISSUE THREAD

**Issue by ronin49** [JeanLucPons/VanitySearch#41]
Hi!
I try this: g++ -c IntGroup.cpp
which gives this:
In file included from IntGroup.h:21,
                 from IntGroup.cpp:18:
Int.h: In function 'void imm_mul(uint64_t*, uint64_t, uint64_t*)':
Int.h:220:32: error: '__builtin_ia32_addcarryx_u64' was not declared in this scope
 #define _addcarry_u64(a,b,c,d) __builtin_ia32_addcarryx_u64(a,b,c,(long long unsigned int*)d);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Int.h:231:7: note: in expansion of macro '_addcarry_u64'
   c = _addcarry_u64(c, _umul128(x[1], y, &h), carry, dst + 1); carry = h;
       ^~~~~~~~~~~~~
Int.h:220:32: note: suggested alternative: '__builtin_ia32_addcarryx_u32'
 #define _addcarry_u64(a,b,c,d) __builtin_ia32_addcarryx_u64(a,b,c,(long long unsigned int*)d);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Int.h:231:7: note: in expansion of macro '_addcarry_u64'
   c = _addcarry_u64(c, _umul128(x[1], y, &h), carry, dst + 1); carry = h;
       ^~~~~~~~~~~~~
Int.h: In function 'void imm_umul(uint64_t*, uint64_t, uint64_t*)':
Int.h:220:32: error: '__builtin_ia32_addcarryx_u64' was not declared in this scope
 #define _addcarry_u64(a,b,c,d) __builtin_ia32_addcarryx_u64(a,b,c,(long long unsigned int*)d);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Int.h:250:7: note: in expansion of macro '_addcarry_u64'
   c = _addcarry_u64(c, _umul128(x[1], y, &h), carry, dst + 1); carry = h;
       ^~~~~~~~~~~~~
Int.h:220:32: note: suggested alternative: '__builtin_ia32_addcarryx_u32'
 #define _addcarry_u64(a,b,c,d) __builtin_ia32_addcarryx_u64(a,b,c,(long long unsigned int*)d);
                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
Int.h:250:7: note: in expansion of macro '_addcarry_u64'
   c = _addcarry_u64(c, _umul128(x[1], y, &h), carry, dst + 1); carry = h;

**Comment by shayanolegator** [comment]
I want to use your Int class in my project)

**Comment by ZielarSRC** [comment]
Compilation should be done by running the command:

**`make all`** 
when using the application only using the CPU

**`make gpu=1 ccap=XX all`**
when using the application with a GPU or CPU
in place of XX, insert the SM number of the architecture of the target SM graphics processor according to the table: https://en.wikipedia.org/wiki/CUDA (If Compute Capability for your card model is 3.0 - the command item above will be **ccap=30**)

**Comment by rs78GT** [comment]
Hi,
I know this thread is hundred years old, but I run this problem just recently. The problem exactly the same.. I tried to compile it in any way: cross-compile it from X86_64; from native armv7-a, from native armv8-a, with and without CUDA of course.

I tried to replace  __builtin_ia32_addcarryx_u64 by a few _arm_builtin function (long long int), the result was worse.
I used gcc-8; 10; etc. The same error again and again. I red somewhere there is no problem with the 64 long on 32 bit arch, so I thought it is possible. The armv8 is 64 bit, so obviously that is not the case.

So, if someone read this, please tell me what is the workaround this compiler problem, if it possible.
Thanks in advance!

Oh, sorry! I forgot to mention: i wanna compile VanitySearch for armv7.
