### ISSUE TITLE
Option to search from list?

### ISSUE THREAD

**Issue by WesNz** [JeanLucPons/VanitySearch#6]
Hi

About to test the program, found it on bitcointalk.
Is there an option to search from a text file list?
Didnt seem to see it

Thanks again

**Comment by JeanLucPons** [comment]
Not yet
it's coming

**Comment by WesNz** [comment]
Awesome! would be cool if it could monitor all addresses at the same time in the list instead of doing it one at a time.  Is the search totally random?

**Comment by JeanLucPons** [comment]
The search is based from a base private key which is random if no seed is specified.
Then the base key is incremented and corresponding public addresses are checked.
VanitySearch also use some symmetry properties of elliptic curve and the base key can also be negated.
(Currently in development)

**Comment by JeanLucPons** [comment]
The new release is ready.
Use the -i inputFile option to specifie a list of prefix.
