### ISSUE TITLE
split-key, -sp generates "PubAddress:", -rp expects "Pub Addr:"

### ISSUE THREAD

**Issue by Eegee** [JeanLucPons/VanitySearch#61]
I was following https://github.com/JeanLucPons/VanitySearch#generate-a-vanity-address-for-a-third-party-using-split-key and I think I found a bug.

When using parameter -sp and -o to generate a keyinfo.txt for a split-key, this generated file cannot be used again with parameter `-rp` because this will give the error `Invalid partialkey info file at line 0 ("Pub Addr: " expected)` .
So in my opinion, in Vanity.cpp, line 693 it should not print `PubAddress` but `Pub Addr`

**Comment by cyberzuchini** [comment]
Thank u i got the same problem and fixed it in my clone by changing line 693:
 <  fprintf(f, "PubAddress: %s\n", addr.c_str()); > 
to 
<  fprintf(f, "Pub Addr: %s\n", addr.c_str());  >
So this works fine!

**Comment by JeanLucPons** [comment]
Fixed in 1.19

**Comment by Eegee** [comment]
Alright. I created a pull request to update README.md
