### ISSUE TITLE
Request for docker image

### ISSUE THREAD

**Issue by ratijas** [JeanLucPons/VanitySearch#63]
Hi,

I see, there's great support for Windows, and even binary .exe is provided on the releases page. But Linux support is limited to build instructions that require installation of CUDA SDK on build machine and knowledge of some CUDA programming basics (#37, #62).

Therefore, it would be nice to have a docker image (or at least instructions on how to create one). I'd say, different versions of `ccap` could become different tags on docker hub.

Besides, similar projects have docker images already:
 - https://hub.docker.com/r/cbeams/vanitygen
 - https://hub.docker.com/r/mpenagar/vanitygen-plus

**Comment by ratijas** [comment]
Whether #66 lands or not, Docker images of VanitySearch already exist on Docker Hub. Currently under my personal namespace: https://hub.docker.com/r/ratijas/vanitysearch.

**Comment by mgpai22** [comment]
@ratijas By any chance could you please provide a docker image for `CCAP=8.6`? I am having issues compiling it on my own. Thank you!
