### ISSUE TITLE
Base Key

### ISSUE THREAD

**Issue by bigvito19** [JeanLucPons/VanitySearch#76]
What exactly is the base key and why we can't manually change it?

**Comment by Jessie-1** [comment]
did you got the answer? how to change the base key?

**Comment by bigvito19** [comment]
> did you got the answer? how to change the base key?

He said you can't change it.

**Comment by Jessie-1** [comment]
@bigvito19 i found someone did it at https://github.com/kanhavishva/KeyHunt-Cuda
