### ISSUE TITLE
How to compile RTX 3090 with vanity search on ubuntu(VM)?

### ISSUE THREAD

**Issue by siupune** [JeanLucPons/VanitySearch#97]
please guide me if anybody has done it.....

**Comment by Jolly-Pirate** [comment]
First, install the CUDA toolkit https://developer.nvidia.com/cuda-downloads , the download and install instructions are given there, I recommend you do the "deb (local)" intallation, it's easier and less problematic than the "runfile (local) "method. Then do this too `sudo apt -y install nvidia-cuda-toolkit`, and reboot (you have to do that).
Check the nvcc version with `nvcc --version` and run `nvidia-smi` to check CUDA and the drivers are all good.
Clone the VanitySearch repo and build with:
```
git clone https://github.com/JeanLucPons/VanitySearch
cd VanitySearch
make gpu=1 CCAP=8.0 CUDA=/usr/local/cuda-11.2 CXXCUDA=/usr/bin/g++ all
```
or
`make gpu=1 CCAP=8.6 CUDA=/usr/local/cuda-11.2 CXXCUDA=/usr/bin/g++ all`
I'm not sure which CCAP version is the one for RTX 3090, and of course use the appropriate CUDA version you installed, e.g. `CUDA=/usr/local/cuda-11.2`, then you should have a `VanitySearch` binary that you can run with `./VanitySearch`. You can copy it to your $HOME/bin folder so it will be accessible from any other folder, and you can run it directly by typing `VanitySearch` (no need for the `./`

There's also another useful tool you can compile:
```
cd /usr/local/cuda-11.2/samples/1_Utilities/deviceQuery
sudo make
sudo cp deviceQuery /usr/bin/
```
And type `deviceQuery` for a detailed info about your GPU.

**Comment by siupune** [comment]
![image](https://user-images.githubusercontent.com/72907883/112012269-10796300-8b4f-11eb-9e04-fa9bed36d60b.png)

**Comment by siupune** [comment]
prabably some bug as i delete few letters from address, it works fine....

**Comment by siupune** [comment]
Thank you sooooooooo much for the help......

**Comment by Jolly-Pirate** [comment]
> Thank you sooooooooo much for the help......
Actually, I should have mentioned to install deviceQuery first, since it gives you the exact CCAP version e.g. `CUDA Capability Major/Minor version number:    7.5`. From what I've read on forums and comments, it's 8.6 for the RTX 3090.

**Comment by siupune** [comment]
i checked kangaroo with ubuntu 20.04 with rtx 3090 and showed these
errors....

**Comment by siupune** [comment]
i checked kangaroo with ubuntu 20.04 with rtx 3090 and showed these
errors....
![kangaroo error](https://user-images.githubusercontent.com/72907883/112114602-4285d600-8bde-11eb-9fca-a5b317b7929c.JPG)

**Comment by siupune** [comment]
> First, install the CUDA toolkit https://developer.nvidia.com/cuda-downloads , the download and install instructions are given there, I recommend you do the "deb (local)" intallation, it's easier and less problematic than the "runfile (local) "method. Then do this too `sudo apt -y install nvidia-cuda-toolkit`, and reboot (you have to do that).
> Check the nvcc version with `nvcc --version` and run `nvidia-smi` to check CUDA and the drivers are all good.
> Clone the VanitySearch repo and build with:
> 
> ```
> git clone https://github.com/JeanLucPons/VanitySearch
> cd VanitySearch
> make gpu=1 CCAP=8.0 CUDA=/usr/local/cuda-11.2 CXXCUDA=/usr/bin/g++ all
> ```
> 
> or
> `make gpu=1 CCAP=8.6 CUDA=/usr/local/cuda-11.2 CXXCUDA=/usr/bin/g++ all`
> I'm not sure which CCAP version is the one for RTX 3090, and of course use the appropriate CUDA version you installed, e.g. `CUDA=/usr/local/cuda-11.2`, then you should have a `VanitySearch` binary that you can run with `./VanitySearch`. You can copy it to your $HOME/bin folder so it will be accessible from any other folder, and you can run it directly by typing `VanitySearch` (no need for the `./`
> 
> There's also another useful tool you can compile:
> 
> ```
> cd /usr/local/cuda-11.2/samples/1_Utilities/deviceQuery
> sudo make
> sudo cp deviceQuery /usr/bin/
> ```
> 
> And type `deviceQuery` for a detailed info about your GPU.

**Comment by Jolly-Pirate** [comment]
> i checked kangaroo with ubuntu 20.04 with rtx 3090 and showed these
> errors....
> ![kangaroo error](https://user-images.githubusercontent.com/72907883/112114602-4285d600-8bde-11eb-9fca-a5b317b7929c.JPG)

Kangaroo uses the old `ccap` make switch (like vanitygen). Use `ccap=86` instead of `CCAP=8.6`.

**Comment by ZielarPL** [comment]
You must edit file named Makefile
Go to the lines 62 and 65 and change "$(ccap)" to "86"

**Comment by Jolly-Pirate** [comment]
> You must edit file named Makefile
> Go to the lines 62 and 65 and change "$(ccap)" to "86"

No need to edit the Makefile, you can pass it as a parameter when you run the `make` command. Besides, it can be tedious to edit everytime if you have multiple and different GPUs.

**Comment by ZielarPL** [comment]
When i try compile few weeks ago - set CCAP=86 give that same error what when use 8.6 so i write checked solution to solve that problem

**Comment by siupune** [comment]
Any Perfect solution?

**Comment by siupune** [comment]
Any suggestions please?????????

**Comment by Jolly-Pirate** [comment]
I've seen that GeForce RTX 3090 (82x0 cores) problem before https://bitcointalk.org/index.php?topic=5112311.msg55773362#msg55773362
Not sure if it was resolved. Can you try downgrading to CUDA 11.1 and recompile it? You can get it here https://developer.nvidia.com/cuda-toolkit-archive

**Comment by siupune** [comment]
Somebody already changed codes for Kangaoo here : https://gitea.datahoarding.agency/ZenulAbidin/Kangaroo-256
just change last line in GPUEngine.cu 86 , 128 not 64. thats all but i came across Segmentation broken(core dumped)

**Comment by siupune** [comment]
i get these error after using these updated kangaroo-256 : https://gitea.datahoarding.agency/ZenulAbidin/Kangaroo-256

![Kangaroo-256 core dumped witout -g](https://user-images.githubusercontent.com/72907883/112721333-4a6caf80-8f29-11eb-8903-da7ad85c73d2.JPG)

**Comment by ZenulAbidin** [comment]
> Somebody already changed codes for Kangaoo here : https://gitea.datahoarding.agency/ZenulAbidin/Kangaroo-256
just change last line in GPUEngine.cu 86 , 128 not 64. thats all but i came across Segmentation broken(core dumped)

Fork author here.

If modification to 128 threads doesn't work then just leave it at the default 64, some A100 cards have less than 128 SMs: https://www.guru3d.com/news-story/nvidia-tesla-a100-with-ga100-ampere-gpu-spotted.html

Now for further debugging I need you to upload a core dump for me. 

Run this command as root:

`echo "/tmp/cores/core.%e.%p.%h.%t" > /proc/sys/kernel/core_pattern`

This will temporarily enable core dumps until you reboot.

Then compile Kangaroo again in debug mode (`make gpu=1 debug=1`) and run the program again and then look for a file called "/tmp/cores/core.something.something.something.something". Upload it so that I can inspect it locally.

**Comment by Radar-7528** [comment]
> я получаю эту ошибку после использования этих обновленных kangaroo-256: https://gitea.datahoarding.agency/ZenulAbidin/Kangaroo-256
> 
> ![Ядро Kangaroo-256 выгружено без -g](https://user-images.githubusercontent.com/72907883/112721333-4a6caf80-8f29-11eb-8903-da7ad85c73d2.JPG)



> я получаю эту ошибку после использования этих обновленных kangaroo-256: https://gitea.datahoarding.agency/ZenulAbidin/Kangaroo-256
> 
> ![Ядро Kangaroo-256 выгружено без -g](https://user-images.githubusercontent.com/72907883/112721333-4a6caf80-8f29-11eb-8903-da7ad85c73d2.JPG)

8 GPU, cool. Need to brute-force passwords wallet.dat....no need to waste time on collisions. Write to me by mail.

**Comment by siupune** [comment]
please send me your telegram id and will message you

**Comment by Radar-7528** [comment]
> please send me your telegram id and will message you
ok. https://t.me/G_Rodary
